### ISSUE TITLE
Solution for different background color appearing.

### ISSUE THREAD

**Issue by huandney** [thiswillbeyourgithub/Oliver_Cloze#1]
First of all, congratulations on the work. As I was unable to open a Pull request, I am posting here.

**- Describe the bug**
When we omit a different color term, the first letter of that term becomes visible:
![1](https://user-images.githubusercontent.com/19948348/99289638-9b4df800-2813-11eb-9e0f-1966a73ac334.JPG)
![2](https://user-images.githubusercontent.com/19948348/99289675-a6a12380-2813-11eb-9dd9-a054050e46af.JPG)

**- Solution**

Add _display: `inline; text-indent: 100%` in _.cloze_ in style. This makes it take off, hiding the text.
![5](https://user-images.githubusercontent.com/19948348/99290610-e7e60300-2814-11eb-97cf-9252d96c6fee.JPG)

**Optional.**  If you want to remove the red color pattern, do the following:
1. In Template Verso, add `item.style.color = "inherit";`  in  _// hides the clozes._
![6](https://user-images.githubusercontent.com/19948348/99291170-c1749780-2815-11eb-9597-9b85e9b1154b.JPG)
2. Change the color to `none` in `.nightMode .cloze {color: none! Important; }` in style. This takes the standardization out of the red color in nigthMode.
![7](https://user-images.githubusercontent.com/19948348/99292410-8d9a7180-2817-11eb-8226-b7f7205314e4.JPG)

**- Result**
![3](https://user-images.githubusercontent.com/19948348/99292426-94c17f80-2817-11eb-8a45-bb245303b755.JPG)
![4](https://user-images.githubusercontent.com/19948348/99292429-95f2ac80-2817-11eb-90ee-708fac39e4d6.JPG)

Note: the layout is different because I customized some parameters.

**- Anki / OS versions**
Anki version 2.1.35
Windows 10

**Comment by thiswillbeyourgithub** [comment]
Hi,

Thanks a lot for taking the time :) It really makes me happy to see this being used.

1. Can you elaborate on why you couldn't make a pull request? Is it something I have to enable or was the issue on your side?
2. This addition looks clean and I will gladly add it to the new version. I added a few things to my personnal template and your contribution is the occasion to roll out the new version. Stay tuned!
3. I don't understand how this :  

>  .nightMode .cloze {color: none! Important; } 

won't interfere with ... using nightmode. Care to explain?

Have a nice day!

**Comment by huandney** [comment]
Hello,

> 1. Can you elaborate on why you couldn't make a pull request? Is it something I have to enable or was the issue on your side?
>
I imagine it is on your side, I don't really understand how github works.

> 2. This addition looks clean and I will gladly add it to the new version. I added a few things to my personnal template and your contribution is the occasion to roll out the new version. Stay tuned!
>
Cool, I can share a deck, with my modifications.

> 3. I don't understand how this :
> 
> > .nightMode .cloze {color: none! Important; }
> 
> won't interfere with ... using nightmode. Care to explain?
>
This change is just so that the answer does not turn red in night mode, as I often want to put it in the standard color, or another custom color. See that this is optional.

**Comment by thiswillbeyourgithub** [comment]
> I imagine it is on your side, I don't really understand how github works.

I'm pretty sure they are not disabled or something but whatever. Github is not really intuitive and my first few PR were surprisingly hard to figure out.

> Cool, I can share a deck, with my modifications.

I'm very eager to implement upstream any cool idea, what do you think of pasting the front back and styling in a new issue instead? I think it would be easier to manage it, albeit not ideal. Be sure to include comments etc if the code is getting complicated.


> This change is just so that the answer does not turn red in night mode, as I often want to put it in the standard color, or another custom color. See that this is optional.

Okay, I'll make a few tests on my side and see if it works for me. Thanks again!

**Comment by thiswillbeyourgithub** [comment]
I did some quick testing and I don't personnaly need the nighmode modification, but I will add it as a comment in the next version of the styling. Thanks!

**Comment by thiswillbeyourgithub** [comment]
Sorry for the avalanche of notification but while I'm at it I have a question. Do you know how in js I can get the equivalent of 

>   .nightmode .var { whatever}

I already us js to do things like that : 
> someField.style.color             = "grey";

But is there something like `someField.style.nightmode.color` ?  That would really help me cleanup a few things.

**Comment by huandney** [comment]
> I'm pretty sure they are not disabled or something but whatever. Github is not really intuitive and my first few PR were surprisingly hard to figure out.
> 
The funny thing is that I did a test in another repository and I got it.

> I'm very eager to implement upstream any cool idea, what do you think of pasting the front back and styling in a new issue instead? I think it would be easier to manage it, albeit not ideal. Be sure to include comments etc if the code is getting complicated.
> 

Can be! Just give me some guidance, since I don't have much experience in cooperating here on github.

> 
> > someField.style.color             = "grey";
> 
> But is there something like `someField.style.nightmode.color` ? That would really help me cleanup a few things.

I don't know, my knowledge of JS is somewhat limited. : /

**Comment by thiswillbeyourgithub** [comment]
> Can be! Just give me some guidance, since I don't have much experience in cooperating here on github.

Just open another github issue and paste the content of each file in a separate message, enclosed in triple `. So there should be 3 comments : front, back and styling.

For example : 
```
content of the file
```


> I don't know, my knowledge of JS is somewhat limited. : /


I'll ask someone else, thanks anyway

And please be sure to comment the code ;)

**Comment by thiswillbeyourgithub** [comment]
After some more testing it appears that 

> inline; text-indent: 100%

Is causing some issues on my template. When unhiding the cloze with n, the text and images appears but the indent is still there. So it ends up putting the first character at the end of  the line and the rest is below it.

I think I was able to fix it by adding 

>             item.style.textIndent      = "0%";

When unhinding the clozes.

**Comment by huandney** [comment]
> After some more testing it appears that
> 
> > inline; text-indent: 100%
> 
> Is causing some issues on my template. When unhiding the cloze with n, the text and images appears but the indent is still there. So it ends up putting the first character at the end of the line and the rest is below it.
> 
> I think I was able to fix it by adding
> 
> > ```
> >         item.style.textIndent      = "0%";
> > ```
> 
> When unhinding the clozes.

Curious, I hardly use an image, but I just did a test, here I didn't have this problem. If you want to share the deck with me, take a look.

**Comment by thiswillbeyourgithub** [comment]
It doesn't happend all the time, there seems to be some way to imbricate <div> that causes it. I first noticed it with bullet points.

Take this example :

![screenshot](https://user-images.githubusercontent.com/26625900/99882544-1dc22780-2c19-11eb-85b2-bff2b1c0e8d7.png)



```
<div><br></div>
<div>{{c1::<div><br></div><div><ul><li>aaaaaaaaaaaaaaaaa</li></ul><div><br></div></div><div></div>}}<br></div><div><br></div>
```


![screenshot_1](https://user-images.githubusercontent.com/26625900/99882563-4813e500-2c19-11eb-98b7-53c6b1d12f35.png)

**Comment by huandney** [comment]
> It doesn't happend all the time, there seems to be some way to imbricate
> 
> that causes it. I first noticed it with bullet points.
> Take this example :
> 
> ![screenshot](https://user-images.githubusercontent.com/26625900/99882544-1dc22780-2c19-11eb-85b2-bff2b1c0e8d7.png)
> 
> ```
> <div><br></div>
> <div>{{c1::<div><br></div><div><ul><li>aaaaaaaaaaaaaaaaa</li></ul><div><br></div></div><div></div>}}<br></div><div><br></div>
> ```
> 
> ![screenshot_1](https://user-images.githubusercontent.com/26625900/99882563-4813e500-2c19-11eb-98b7-53c6b1d12f35.png)

Change `text-indent: 100%` with `text-indent: -5px`

**Comment by huandney** [comment]
> It doesn't happend all the time, there seems to be some way to imbricate
> 
> that causes it. I first noticed it with bullet points.
> Take this example :
> 
> ![screenshot](https://user-images.githubusercontent.com/26625900/99882544-1dc22780-2c19-11eb-85b2-bff2b1c0e8d7.png)
> 
> ```
> <div><br></div>
> <div>{{c1::<div><br></div><div><ul><li>aaaaaaaaaaaaaaaaa</li></ul><div><br></div></div><div></div>}}<br></div><div><br></div>
> ```
> 
> ![screenshot_1](https://user-images.githubusercontent.com/26625900/99882563-4813e500-2c19-11eb-98b7-53c6b1d12f35.png)

I thought about this solution for now:
add in style
```
ul {
text-indent: -1px;
}
ol {
text-indent: -1px;
}
```

**Comment by thiswillbeyourgithub** [comment]
Thanks for the suggestion. But how can this be better than just indenting when hiding the cloze and unindenting it when revealing the cloze?  [cf this](https://github.com/thiswillbeyourgithub/Clozolkor/issues/1#issuecomment-729983075)

I don't think your last suggestion is better, but given my understanding of js I would not be surprised to see that it causes unforeseen problems.
