### ISSUE TITLE
Have a purer template

### ISSUE THREAD

**Issue by TheMystery28** [thiswillbeyourgithub/Oliver_Cloze#10]
All is in the title, I only want your special cloze feature without the rest. I know a little about html but your template is complex enough for me to don't make a successful modification.
Could you please help me?

**Comment by thiswillbeyourgithub** [comment]
Hi,


sure, I can help. But I need to know more specifically what you need.

Clozolkor allows to show clozes one by one, but also letter by letter or word by word, do you care about that?

Also, it automatically flips from front to back to only hide the cloze while avoiding having to press the space bar every time, do you care about that?

Also, have you checked the alternatives like cloze overlapper, closet, and others? It might be more relevant to you.

**Comment by TheMystery28** [comment]
I do not want the header and font changes. if possible.
I already use the add-ons you mentioned but none of them have the "unfold cloze one-by-one".

**Comment by thiswillbeyourgithub** [comment]
I think it would be easier for everyone if you made it yourself by commenting lines. Just add "//" at the beginning of a javascript line and see if it doesn't break things. I think it would be less likely to break things than removing html lines (using ).

The way I see it, there are like 20 times more lines in my code to setup an action and then one to activate it. For example, the header needs lots of lines to be setup but in the end there are very few lines that you need to comment to make them useless. Hence "purifying" the rendered template.

I know it's going to leave a very long template and be quite messy but I don't feel like it's worth our collective time.

So try adding // in the js lines that activate sections you don't care about.

Also, don't forget that there is a certain number of "settings" that you can turn on or off in the back template, maybe that's already enough for you.

Don't hesitate to come back here if you have any issue or question.
