### ISSUE TITLE
Bug when revealing letter.

### ISSUE THREAD

**Issue by huandney** [thiswillbeyourgithub/Oliver_Cloze#7]
Sorry to bother you again.
When we are revealing the cloze in a disordered way in the last (or depending on the quantity, the last) cloze, the revelation by letter does not work:
![error](https://user-images.githubusercontent.com/19948348/113507134-ab424c00-9516-11eb-9228-b7e848c60145.gif)
![errosd](https://user-images.githubusercontent.com/19948348/113507135-ac737900-9516-11eb-879f-ed6ef1b62948.gif)

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks for the catch!


I found a fix, some code written a long time ago that should not have been where it was :/

I will test it for a few days and if I don't see any issue that arise I will push it on github.

In the meantime, if you feel risky and want to try the new back.js here it is, but keep in mind that I have not tested it yet : 

[back.zip](https://github.com/thiswillbeyourgithub/Clozolkor/files/6258970/back.zip)

oh and

> sorry to bother you again.

**slaps you in the face and hugs you**
All issues and remarks are always appreciated! FOSS for the win!

**Comment by huandney** [comment]
Apparently it is working very well, but you forgot to add the implement of:
https://github.com/thiswillbeyourgithub/Clozolkor/issues/5

I tried to add by pasting manuallyClicked it worked more broke the solution of this issue.

**Comment by thiswillbeyourgithub** [comment]
Hi,
thanks a lot for the very useful report.

I spent way too much time today on this. Unfortunately this is quite tricky and this terrible pasta code is making really hard to not break 3 things when fixing one so I will need more time for this. (I really like clean code but ffs js in anki makes you jump through implausible hoops to no end to work so I ended up with ugly code)

Sorry :/ I will try things on and on. Don't hesitate to remind me if this really seems like I forgot.

Thanks again!

**Comment by thiswillbeyourgithub** [comment]
Surprisingly I procrastinated a whole lot today and ended up coding this. Check out the new files (front, back and styling) and don't hesitate to tell me if anything goes wrong! The whole code is now much clearer.

Thanks again!

**Comment by huandney** [comment]
First of all, I want to thank you for your work.
Everything works fine, except when we reveal it by the rectangle, in a disorderly way, the "Hint" does not open. The same goes for the shortcut:
![Test](https://user-images.githubusercontent.com/19948348/113781844-4e55ba00-96ff-11eb-9d71-7d89ad059ba7.gif)

I also found a strange random behavior, when we reveal the letters in a disorderly way, sometimes the "Hint" opens in advance:
![aleatorio](https://user-images.githubusercontent.com/19948348/113781999-8230df80-96ff-11eb-8dd2-22c9deea7ba6.gif)

**Comment by thiswillbeyourgithub** [comment]
Thanks! Test the new files again please :)

**Comment by huandney** [comment]
Thank you very much, it's working perfectly.

**Comment by thiswillbeyourgithub** [comment]
Great to know! Don"t forget that it's also thanks to you :) it allowed me to do a great deal of cleanup and I would not have noticed otherwise.

Thanks!
