### ISSUE TITLE
Not working here?

### ISSUE THREAD

**Issue by gabrielpacosta** [thiswillbeyourgithub/Oliver_Cloze#8]
Is it suppose to work on Anki Version ⁨2.1.42 (8eebfe18)⁩?

**Comment by thiswillbeyourgithub** [comment]
Hi!

I don't know! I won't have the chance to upgrade anki before the summer, am still using anki 2.1.35. If you want to try please let me know!

**Comment by thiswillbeyourgithub** [comment]
Hello again! I uploaded the last version and it's apparently working on 2.1.44 so far.

**Comment by thiswillbeyourgithub** [comment]
It's working fine on 2.1.49.
